name       : lilyterm
version    : 0.9.9.4
release    : 1
source     :
    - http://lilyterm.luna.com.tw/file/lilyterm-0.9.9.4.tar.gz : b72626431d4f5645e0e0f18449319fbb69bef4eab4345d5e37cde0ae712a5d74
license    : GPL-3.0
component  : system.util
summary    : Terminal Emulator
description: |
    LilyTerm is a terminal emulator based off of libvte that aims to be fast and lightweight.
builddeps  :
    - pkgconfig(vte)
    - gettext-devel
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
