name       : lilyterm
version    : 0.9.9.4
release    : 2
source     :
    - https://github.com/Tetralet/LilyTerm/archive/v0.9.9.4.tar.gz : 310cafcc6c155db1862ee42bd2d57da5083d8f6616ffa3a50083113c06846c3a
license    : GPL-3.0-or-later
component  : system.util
summary    : Terminal Emulator
description: |
    LilyTerm is a terminal emulator based off of libvte that aims to be fast and lightweight.
builddeps  :
    - pkgconfig(vte)
    - gettext-devel
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
